#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Jan 18, 2021 10:59:48 PM CET  platform: Linux

import sys
import subprocess

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def imageInfo_click(self):
    
    with open("imageinfo", "w") as file:
        proc = []
        proc.append(subprocess.Popen(
            ['./volatility_2.6_lin64_standalone','-f','Dump.mem','imageinfo'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True,
            shell=False,
            ))
        file.write(proc[0].communicate()[0])
        file.close()
    
    with open("imageinfo", "r") as file:
        w.TextImageInfo.insert(tk.END, file.read())
    #ttk.Label(tab0, text=f.read()).pack()

    sys.stdout.flush()

def start_click():
    print('volagui_support.start_click')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import volagui
    volagui.vp_start_gui()



